export const indonesiaRegions = [
  { value: "kabupaten-aceh-barat-aceh", label: "Kabupaten Aceh Barat - Aceh" },
  { value: "kabupaten-aceh-barat-daya-aceh", label: "Kabupaten Aceh Barat Daya - Aceh" },
  { value: "kabupaten-aceh-besar-aceh", label: "Kabupaten Aceh Besar - Aceh" },
  { value: "kabupaten-aceh-jaya-aceh", label: "Kabupaten Aceh Jaya - Aceh" },
  { value: "kabupaten-aceh-selatan-aceh", label: "Kabupaten Aceh Selatan - Aceh" },
  { value: "kabupaten-aceh-singkil-aceh", label: "Kabupaten Aceh Singkil - Aceh" },
  { value: "kabupaten-aceh-tamiang-aceh", label: "Kabupaten Aceh Tamiang - Aceh" },
  { value: "kabupaten-aceh-tengah-aceh", label: "Kabupaten Aceh Tengah - Aceh" },
  { value: "kabupaten-aceh-tenggara-aceh", label: "Kabupaten Aceh Tenggara - Aceh" },
  { value: "kabupaten-aceh-timur-aceh", label: "Kabupaten Aceh Timur - Aceh" },
  { value: "kabupaten-aceh-utara-aceh", label: "Kabupaten Aceh Utara - Aceh" },
  { value: "kota-banda-aceh-aceh", label: "Kota Banda Aceh - Aceh" },
  { value: "kota-langsa-aceh", label: "Kota Langsa - Aceh" },
  { value: "kota-lhokseumawe-aceh", label: "Kota Lhokseumawe - Aceh" },
  { value: "kota-sabang-aceh", label: "Kota Sabang - Aceh" },
  { value: "kota-subulussalam-aceh", label: "Kota Subulussalam - Aceh" },
  
  { value: "kabupaten-asahan-sumatera-utara", label: "Kabupaten Asahan - Sumatera Utara" },
  { value: "kabupaten-batubara-sumatera-utara", label: "Kabupaten Batubara - Sumatera Utara" },
  { value: "kabupaten-dairi-sumatera-utara", label: "Kabupaten Dairi - Sumatera Utara" },
  { value: "kabupaten-deli-serdang-sumatera-utara", label: "Kabupaten Deli Serdang - Sumatera Utara" },
  { value: "kabupaten-humbang-hasundutan-sumatera-utara", label: "Kabupaten Humbang Hasundutan - Sumatera Utara" },
  { value: "kabupaten-karo-sumatera-utara", label: "Kabupaten Karo - Sumatera Utara" },
  { value: "kabupaten-labuhanbatu-sumatera-utara", label: "Kabupaten Labuhanbatu - Sumatera Utara" },
  { value: "kabupaten-langkat-sumatera-utara", label: "Kabupaten Langkat - Sumatera Utara" },
  { value: "kabupaten-mandailing-natal-sumatera-utara", label: "Kabupaten Mandailing Natal - Sumatera Utara" },
  { value: "kabupaten-nias-sumatera-utara", label: "Kabupaten Nias - Sumatera Utara" },
  { value: "kabupaten-padang-lawas-sumatera-utara", label: "Kabupaten Padang Lawas - Sumatera Utara" },
  { value: "kabupaten-simalungun-sumatera-utara", label: "Kabupaten Simalungun - Sumatera Utara" },
  { value: "kabupaten-tapanuli-selatan-sumatera-utara", label: "Kabupaten Tapanuli Selatan - Sumatera Utara" },
  { value: "kabupaten-tapanuli-tengah-sumatera-utara", label: "Kabupaten Tapanuli Tengah - Sumatera Utara" },
  { value: "kabupaten-tapanuli-utara-sumatera-utara", label: "Kabupaten Tapanuli Utara - Sumatera Utara" },
  { value: "kabupaten-toba-sumatera-utara", label: "Kabupaten Toba - Sumatera Utara" },
  { value: "kota-binjai-sumatera-utara", label: "Kota Binjai - Sumatera Utara" },
  { value: "kota-medan-sumatera-utara", label: "Kota Medan - Sumatera Utara" },
  { value: "kota-padangsidimpuan-sumatera-utara", label: "Kota Padangsidimpuan - Sumatera Utara" },
  { value: "kota-pematangsiantar-sumatera-utara", label: "Kota Pematangsiantar - Sumatera Utara" },
  { value: "kota-tanjungbalai-sumatera-utara", label: "Kota Tanjungbalai - Sumatera Utara" },
  { value: "kota-tebing-tinggi-sumatera-utara", label: "Kota Tebing Tinggi - Sumatera Utara" },

  { value: "kabupaten-agam-sumatera-barat", label: "Kabupaten Agam - Sumatera Barat" },
  { value: "kabupaten-dharmasraya-sumatera-barat", label: "Kabupaten Dharmasraya - Sumatera Barat" },
  { value: "kabupaten-kepulauan-mentawai-sumatera-barat", label: "Kabupaten Kepulauan Mentawai - Sumatera Barat" },
  { value: "kabupaten-lima-puluh-kota-sumatera-barat", label: "Kabupaten Lima Puluh Kota - Sumatera Barat" },
  { value: "kabupaten-padang-pariaman-sumatera-barat", label: "Kabupaten Padang Pariaman - Sumatera Barat" },
  { value: "kabupaten-pasaman-sumatera-barat", label: "Kabupaten Pasaman - Sumatera Barat" },
  { value: "kabupaten-pesisir-selatan-sumatera-barat", label: "Kabupaten Pesisir Selatan - Sumatera Barat" },
  { value: "kabupaten-sijunjung-sumatera-barat", label: "Kabupaten Sijunjung - Sumatera Barat" },
  { value: "kabupaten-solok-sumatera-barat", label: "Kabupaten Solok - Sumatera Barat" },
  { value: "kabupaten-tanah-datar-sumatera-barat", label: "Kabupaten Tanah Datar - Sumatera Barat" },
  { value: "kota-bukittinggi-sumatera-barat", label: "Kota Bukittinggi - Sumatera Barat" },
  { value: "kota-padang-sumatera-barat", label: "Kota Padang - Sumatera Barat" },
  { value: "kota-padangpanjang-sumatera-barat", label: "Kota Padangpanjang - Sumatera Barat" },
  { value: "kota-pariaman-sumatera-barat", label: "Kota Pariaman - Sumatera Barat" },
  { value: "kota-payakumbuh-sumatera-barat", label: "Kota Payakumbuh - Sumatera Barat" },
  { value: "kota-sawahlunto-sumatera-barat", label: "Kota Sawahlunto - Sumatera Barat" },
  { value: "kota-solok-sumatera-barat", label: "Kota Solok - Sumatera Barat" },

  { value: "kabupaten-bengkalis-riau", label: "Kabupaten Bengkalis - Riau" },
  { value: "kabupaten-indragiri-hilir-riau", label: "Kabupaten Indragiri Hilir - Riau" },
  { value: "kabupaten-indragiri-hulu-riau", label: "Kabupaten Indragiri Hulu - Riau" },
  { value: "kabupaten-kampar-riau", label: "Kabupaten Kampar - Riau" },
  { value: "kabupaten-kepulauan-meranti-riau", label: "Kabupaten Kepulauan Meranti - Riau" },
  { value: "kabupaten-kuantan-singingi-riau", label: "Kabupaten Kuantan Singingi - Riau" },
  { value: "kabupaten-pelalawan-riau", label: "Kabupaten Pelalawan - Riau" },
  { value: "kabupaten-rokan-hilir-riau", label: "Kabupaten Rokan Hilir - Riau" },
  { value: "kabupaten-rokan-hulu-riau", label: "Kabupaten Rokan Hulu - Riau" },
  { value: "kabupaten-siak-riau", label: "Kabupaten Siak - Riau" },
  { value: "kota-dumai-riau", label: "Kota Dumai - Riau" },
  { value: "kota-pekanbaru-riau", label: "Kota Pekanbaru - Riau" },

  { value: "kabupaten-bandung-jawa-barat", label: "Kabupaten Bandung - Jawa Barat" },
  { value: "kabupaten-bandung-barat-jawa-barat", label: "Kabupaten Bandung Barat - Jawa Barat" },
  { value: "kabupaten-bekasi-jawa-barat", label: "Kabupaten Bekasi - Jawa Barat" },
  { value: "kabupaten-bogor-jawa-barat", label: "Kabupaten Bogor - Jawa Barat" },
  { value: "kabupaten-ciamis-jawa-barat", label: "Kabupaten Ciamis - Jawa Barat" },
  { value: "kabupaten-cianjur-jawa-barat", label: "Kabupaten Cianjur - Jawa Barat" },
  { value: "kabupaten-cirebon-jawa-barat", label: "Kabupaten Cirebon - Jawa Barat" },
  { value: "kabupaten-garut-jawa-barat", label: "Kabupaten Garut - Jawa Barat" },
  { value: "kabupaten-indramayu-jawa-barat", label: "Kabupaten Indramayu - Jawa Barat" },
  { value: "kabupaten-karawang-jawa-barat", label: "Kabupaten Karawang - Jawa Barat" },
  { value: "kabupaten-kuningan-jawa-barat", label: "Kabupaten Kuningan - Jawa Barat" },
  { value: "kabupaten-majalengka-jawa-barat", label: "Kabupaten Majalengka - Jawa Barat" },
  { value: "kabupaten-pangandaran-jawa-barat", label: "Kabupaten Pangandaran - Jawa Barat" },
  { value: "kabupaten-purwakarta-jawa-barat", label: "Kabupaten Purwakarta - Jawa Barat" },
  { value: "kabupaten-subang-jawa-barat", label: "Kabupaten Subang - Jawa Barat" },
  { value: "kabupaten-sukabumi-jawa-barat", label: "Kabupaten Sukabumi - Jawa Barat" },
  { value: "kabupaten-sumedang-jawa-barat", label: "Kabupaten Sumedang - Jawa Barat" },
  { value: "kabupaten-tasikmalaya-jawa-barat", label: "Kabupaten Tasikmalaya - Jawa Barat" },
  { value: "kota-bandung-jawa-barat", label: "Kota Bandung - Jawa Barat" },
  { value: "kota-banjar-jawa-barat", label: "Kota Banjar - Jawa Barat" },
  { value: "kota-bekasi-jawa-barat", label: "Kota Bekasi - Jawa Barat" },
  { value: "kota-bogor-jawa-barat", label: "Kota Bogor - Jawa Barat" },
  { value: "kota-cimahi-jawa-barat", label: "Kota Cimahi - Jawa Barat" },
  { value: "kota-cirebon-jawa-barat", label: "Kota Cirebon - Jawa Barat" },
  { value: "kota-depok-jawa-barat", label: "Kota Depok - Jawa Barat" },
  { value: "kota-sukabumi-jawa-barat", label: "Kota Sukabumi - Jawa Barat" },
  { value: "kota-tasikmalaya-jawa-barat", label: "Kota Tasikmalaya - Jawa Barat" },

  { value: "kabupaten-banjarnegara-jawa-tengah", label: "Kabupaten Banjarnegara - Jawa Tengah" },
  { value: "kabupaten-banyumas-jawa-tengah", label: "Kabupaten Banyumas - Jawa Tengah" },
  { value: "kabupaten-batang-jawa-tengah", label: "Kabupaten Batang - Jawa Tengah" },
  { value: "kabupaten-blora-jawa-tengah", label: "Kabupaten Blora - Jawa Tengah" },
  { value: "kabupaten-boyolali-jawa-tengah", label: "Kabupaten Boyolali - Jawa Tengah" },
  { value: "kabupaten-brebes-jawa-tengah", label: "Kabupaten Brebes - Jawa Tengah" },
  { value: "kabupaten-cilacap-jawa-tengah", label: "Kabupaten Cilacap - Jawa Tengah" },
  { value: "kabupaten-demak-jawa-tengah", label: "Kabupaten Demak - Jawa Tengah" },
  { value: "kabupaten-grobogan-jawa-tengah", label: "Kabupaten Grobogan - Jawa Tengah" },
  { value: "kabupaten-jepara-jawa-tengah", label: "Kabupaten Jepara - Jawa Tengah" },
  { value: "kabupaten-karanganyar-jawa-tengah", label: "Kabupaten Karanganyar - Jawa Tengah" },
  { value: "kabupaten-kebumen-jawa-tengah", label: "Kabupaten Kebumen - Jawa Tengah" },
  { value: "kabupaten-kendal-jawa-tengah", label: "Kabupaten Kendal - Jawa Tengah" },
  { value: "kabupaten-klaten-jawa-tengah", label: "Kabupaten Klaten - Jawa Tengah" },
  { value: "kabupaten-kudus-jawa-tengah", label: "Kabupaten Kudus - Jawa Tengah" },
  { value: "kabupaten-magelang-jawa-tengah", label: "Kabupaten Magelang - Jawa Tengah" },
  { value: "kabupaten-pati-jawa-tengah", label: "Kabupaten Pati - Jawa Tengah" },
  { value: "kabupaten-pekalongan-jawa-tengah", label: "Kabupaten Pekalongan - Jawa Tengah" },
  { value: "kabupaten-pemalang-jawa-tengah", label: "Kabupaten Pemalang - Jawa Tengah" },
  { value: "kabupaten-purbalingga-jawa-tengah", label: "Kabupaten Purbalingga - Jawa Tengah" },
  { value: "kabupaten-purworejo-jawa-tengah", label: "Kabupaten Purworejo - Jawa Tengah" },
  { value: "kabupaten-rembang-jawa-tengah", label: "Kabupaten Rembang - Jawa Tengah" },
  { value: "kabupaten-semarang-jawa-tengah", label: "Kabupaten Semarang - Jawa Tengah" },
  { value: "kabupaten-sragen-jawa-tengah", label: "Kabupaten Sragen - Jawa Tengah" },
  { value: "kabupaten-sukoharjo-jawa-tengah", label: "Kabupaten Sukoharjo - Jawa Tengah" },
  { value: "kabupaten-tegal-jawa-tengah", label: "Kabupaten Tegal - Jawa Tengah" },
  { value: "kabupaten-temanggung-jawa-tengah", label: "Kabupaten Temanggung - Jawa Tengah" },
  { value: "kabupaten-wonogiri-jawa-tengah", label: "Kabupaten Wonogiri - Jawa Tengah" },
  { value: "kabupaten-wonosobo-jawa-tengah", label: "Kabupaten Wonosobo - Jawa Tengah" },
  { value: "kota-magelang-jawa-tengah", label: "Kota Magelang - Jawa Tengah" },
  { value: "kota-pekalongan-jawa-tengah", label: "Kota Pekalongan - Jawa Tengah" },
  { value: "kota-salatiga-jawa-tengah", label: "Kota Salatiga - Jawa Tengah" },
  { value: "kota-semarang-jawa-tengah", label: "Kota Semarang - Jawa Tengah" },
  { value: "kota-surakarta-jawa-tengah", label: "Kota Surakarta - Jawa Tengah" },
  { value: "kota-tegal-jawa-tengah", label: "Kota Tegal - Jawa Tengah" },

  { value: "kabupaten-bantul-di-yogyakarta", label: "Kabupaten Bantul - DI Yogyakarta" },
  { value: "kabupaten-gunung-kidul-di-yogyakarta", label: "Kabupaten Gunung Kidul - DI Yogyakarta" },
  { value: "kabupaten-kulon-progo-di-yogyakarta", label: "Kabupaten Kulon Progo - DI Yogyakarta" },
  { value: "kabupaten-sleman-di-yogyakarta", label: "Kabupaten Sleman - DI Yogyakarta" },
  { value: "kota-yogyakarta-di-yogyakarta", label: "Kota Yogyakarta - DI Yogyakarta" },

  { value: "kabupaten-bangkalan-jawa-timur", label: "Kabupaten Bangkalan - Jawa Timur" },
  { value: "kabupaten-banyuwangi-jawa-timur", label: "Kabupaten Banyuwangi - Jawa Timur" },
  { value: "kabupaten-blitar-jawa-timur", label: "Kabupaten Blitar - Jawa Timur" },
  { value: "kabupaten-bojonegoro-jawa-timur", label: "Kabupaten Bojonegoro - Jawa Timur" },
  { value: "kabupaten-bondowoso-jawa-timur", label: "Kabupaten Bondowoso - Jawa Timur" },
  { value: "kabupaten-gresik-jawa-timur", label: "Kabupaten Gresik - Jawa Timur" },
  { value: "kabupaten-jember-jawa-timur", label: "Kabupaten Jember - Jawa Timur" },
  { value: "kabupaten-jombang-jawa-timur", label: "Kabupaten Jombang - Jawa Timur" },
  { value: "kabupaten-kediri-jawa-timur", label: "Kabupaten Kediri - Jawa Timur" },
  { value: "kabupaten-lamongan-jawa-timur", label: "Kabupaten Lamongan - Jawa Timur" },
  { value: "kabupaten-lumajang-jawa-timur", label: "Kabupaten Lumajang - Jawa Timur" },
  { value: "kabupaten-madiun-jawa-timur", label: "Kabupaten Madiun - Jawa Timur" },
  { value: "kabupaten-magetan-jawa-timur", label: "Kabupaten Magetan - Jawa Timur" },
  { value: "kabupaten-malang-jawa-timur", label: "Kabupaten Malang - Jawa Timur" },
  { value: "kabupaten-mojokerto-jawa-timur", label: "Kabupaten Mojokerto - Jawa Timur" },
  { value: "kabupaten-nganjuk-jawa-timur", label: "Kabupaten Nganjuk - Jawa Timur" },
  { value: "kabupaten-ngawi-jawa-timur", label: "Kabupaten Ngawi - Jawa Timur" },
  { value: "kabupaten-pacitan-jawa-timur", label: "Kabupaten Pacitan - Jawa Timur" },
  { value: "kabupaten-pamekasan-jawa-timur", label: "Kabupaten Pamekasan - Jawa Timur" },
  { value: "kabupaten-pasuruan-jawa-timur", label: "Kabupaten Pasuruan - Jawa Timur" },
  { value: "kabupaten-ponorogo-jawa-timur", label: "Kabupaten Ponorogo - Jawa Timur" },
  { value: "kabupaten-probolinggo-jawa-timur", label: "Kabupaten Probolinggo - Jawa Timur" },
  { value: "kabupaten-sampang-jawa-timur", label: "Kabupaten Sampang - Jawa Timur" },
  { value: "kabupaten-sidoarjo-jawa-timur", label: "Kabupaten Sidoarjo - Jawa Timur" },
  { value: "kabupaten-situbondo-jawa-timur", label: "Kabupaten Situbondo - Jawa Timur" },
  { value: "kabupaten-sumenep-jawa-timur", label: "Kabupaten Sumenep - Jawa Timur" },
  { value: "kabupaten-trenggalek-jawa-timur", label: "Kabupaten Trenggalek - Jawa Timur" },
  { value: "kabupaten-tuban-jawa-timur", label: "Kabupaten Tuban - Jawa Timur" },
  { value: "kabupaten-tulungagung-jawa-timur", label: "Kabupaten Tulungagung - Jawa Timur" },
  { value: "kota-batu-jawa-timur", label: "Kota Batu - Jawa Timur" },
  { value: "kota-blitar-jawa-timur", label: "Kota Blitar - Jawa Timur" },
  { value: "kota-kediri-jawa-timur", label: "Kota Kediri - Jawa Timur" },
  { value: "kota-madiun-jawa-timur", label: "Kota Madiun - Jawa Timur" },
  { value: "kota-malang-jawa-timur", label: "Kota Malang - Jawa Timur" },
  { value: "kota-mojokerto-jawa-timur", label: "Kota Mojokerto - Jawa Timur" },
  { value: "kota-pasuruan-jawa-timur", label: "Kota Pasuruan - Jawa Timur" },
  { value: "kota-probolinggo-jawa-timur", label: "Kota Probolinggo - Jawa Timur" },
  { value: "kota-surabaya-jawa-timur", label: "Kota Surabaya - Jawa Timur" },

  { value: "kabupaten-badung-bali", label: "Kabupaten Badung - Bali" },
  { value: "kabupaten-bangli-bali", label: "Kabupaten Bangli - Bali" },
  { value: "kabupaten-buleleng-bali", label: "Kabupaten Buleleng - Bali" },
  { value: "kabupaten-gianyar-bali", label: "Kabupaten Gianyar - Bali" },
  { value: "kabupaten-jembrana-bali", label: "Kabupaten Jembrana - Bali" },
  { value: "kabupaten-karangasem-bali", label: "Kabupaten Karangasem - Bali" },
  { value: "kabupaten-klungkung-bali", label: "Kabupaten Klungkung - Bali" },
  { value: "kabupaten-tabanan-bali", label: "Kabupaten Tabanan - Bali" },
  { value: "kota-denpasar-bali", label: "Kota Denpasar - Bali" },

  { value: "kota-jakarta-pusat-dki-jakarta", label: "Kota Jakarta Pusat - DKI Jakarta" },
  { value: "kota-jakarta-utara-dki-jakarta", label: "Kota Jakarta Utara - DKI Jakarta" },
  { value: "kota-jakarta-barat-dki-jakarta", label: "Kota Jakarta Barat - DKI Jakarta" },
  { value: "kota-jakarta-selatan-dki-jakarta", label: "Kota Jakarta Selatan - DKI Jakarta" },
  { value: "kota-jakarta-timur-dki-jakarta", label: "Kota Jakarta Timur - DKI Jakarta" },
  { value: "kabupaten-kepulauan-seribu-dki-jakarta", label: "Kabupaten Kepulauan Seribu - DKI Jakarta" },
];

export const countryCodes = [
  { value: "+62", label: "Indonesia", flag: "🇮🇩", country: "Indonesia" },
  { value: "+1", label: "United States", flag: "🇺🇸", country: "United States" },
  { value: "+44", label: "United Kingdom", flag: "🇬🇧", country: "United Kingdom" },
  { value: "+86", label: "China", flag: "🇨🇳", country: "China" },
  { value: "+81", label: "Japan", flag: "🇯🇵", country: "Japan" },
  { value: "+82", label: "South Korea", flag: "🇰🇷", country: "South Korea" },
  { value: "+65", label: "Singapore", flag: "🇸🇬", country: "Singapore" },
  { value: "+60", label: "Malaysia", flag: "🇲🇾", country: "Malaysia" },
  { value: "+66", label: "Thailand", flag: "🇹🇭", country: "Thailand" },
  { value: "+84", label: "Vietnam", flag: "🇻🇳", country: "Vietnam" },
  { value: "+63", label: "Philippines", flag: "🇵🇭", country: "Philippines" },
  { value: "+91", label: "India", flag: "🇮🇳", country: "India" },
  { value: "+61", label: "Australia", flag: "🇦🇺", country: "Australia" },
  { value: "+64", label: "New Zealand", flag: "🇳🇿", country: "New Zealand" },
  { value: "+49", label: "Germany", flag: "🇩🇪", country: "Germany" },
  { value: "+33", label: "France", flag: "🇫🇷", country: "France" },
  { value: "+39", label: "Italy", flag: "🇮🇹", country: "Italy" },
  { value: "+34", label: "Spain", flag: "🇪🇸", country: "Spain" },
  { value: "+31", label: "Netherlands", flag: "🇳🇱", country: "Netherlands" },
  { value: "+41", label: "Switzerland", flag: "🇨🇭", country: "Switzerland" },
  { value: "+46", label: "Sweden", flag: "🇸🇪", country: "Sweden" },
  { value: "+47", label: "Norway", flag: "🇳🇴", country: "Norway" },
  { value: "+45", label: "Denmark", flag: "🇩🇰", country: "Denmark" },
  { value: "+358", label: "Finland", flag: "🇫🇮", country: "Finland" },
  { value: "+7", label: "Russia", flag: "🇷🇺", country: "Russia" },
  { value: "+55", label: "Brazil", flag: "🇧🇷", country: "Brazil" },
  { value: "+52", label: "Mexico", flag: "🇲🇽", country: "Mexico" },
  { value: "+54", label: "Argentina", flag: "🇦🇷", country: "Argentina" },
  { value: "+27", label: "South Africa", flag: "🇿🇦", country: "South Africa" },
  { value: "+20", label: "Egypt", flag: "🇪🇬", country: "Egypt" },
  { value: "+971", label: "United Arab Emirates", flag: "🇦🇪", country: "United Arab Emirates" },
  { value: "+966", label: "Saudi Arabia", flag: "🇸🇦", country: "Saudi Arabia" },
  { value: "+90", label: "Turkey", flag: "🇹🇷", country: "Turkey" },
];
